language: d

d:
    - dmd

addons:
    apt:
        packages:
        - noweb

script:
    - ./configure
    - make
    - make clean
#   - notangle -Rtest-driver src/keikai.d.noweb > keikai_test.d
#   - $DC -Incurses -L-lncurses -unittest -main -run keikai_test.d
