language: d

env: DTESTFLAGS="-unittest -run -main -Incurses -L-lncurses"

d:
    - dmd

addons:
    apt:
        packages:
        - noweb

script:
    - notangle -Rtest-driver src/keikai.d.noweb > keikai_test.d
    - $DC $DTESTFLAGS keikai_test.d
