language: d

env: DTESTFLAGS=-unittest -run -main -Incurses -L-lncurses

d:
    - dmd
    - ldc
    - gdc

matrix:
    allow_failures:
        d:
            - gdc

addons:
    apt:
        packages:
        - noweb

script: make test DTESTFLAGS=$DTESTFLAGS
