language: d

d:
    - dmd

addons:
    apt:
        packages:
        - noweb

script:
    - notangle -Rtest-driver src/keikai.d.noweb > keikai_test.d
    - $DC -Incurses -L-lncurses -unittest -main -run keikai_test.d
